### ISSUE TITLE
Autofocus is effectively disabled

### ISSUE THREAD

**Issue by ericboehs** [thoughtbot/sky-labels#17]
Using `autofocus` on a sky label isn't possible as [src/sky-labels.js#L18](https://github.com/thoughtbot/sky-labels/blob/master/src/sky-labels.js#L18) blurs any `.sky-label` on document ready ([#L5](https://github.com/thoughtbot/sky-labels/blob/master/src/sky-labels.js#L5)).

From the name of the method, it sounds like it should check if the field has text before blurring but I'm not sure how that's helpful either. Perhaps it was meant to be for hiding other labels when a new one gains focus? But the `blur` trigger handles that.

I think both the document ready call and the function `hideLabelsIfInputHasText` can be removed. I haven't tested this though.

As a work around I'm doing this in my application js:

``` coffee
setTimeout ->
  $('[autofocus]').focus()
, 50
```

The timeout is necessary as the execute order (at least via Rails' asset pipeline) is my code first, then gem js assets.

**Comment by paulcsmith** [comment]
@ericboehs The reason for that code is that when a form is loaded that already has text, the label should be hidden so that it doesn't cover the text. You are right though that it breaks autofocus behavior. 

I'll work on a solution in the next week or so. Maybe there is a way I can do it with pure CSS that removes the need for the JS, or maybe I call `$('[autofocus]').focus()` after blurring the elements.  We'll see what can be done! Thanks for reporting.

**Comment by ericboehs** [comment]
Perhaps `$(".sky-label-has-text").trigger("blur");` instead?

**Comment by ericboehs** [comment]
Also it [doesn't look like](http://stackoverflow.com/questions/8639282/notempty-css-selector-is-not-working) a pure CSS solution exists.

**Comment by paulcsmith** [comment]
Problem with `$(".sky-label-has-text").trigger("blur");` is that if the field with `autofocus` has text then it will be blurred :(

**Comment by ericboehs** [comment]
`$('.sky-label-has-text').filter(":not(:has([autofocus]))").trigger("blur");`

Edit: Just tested. This doesn't work as expected either. I think simply adding `$('[autofocus]').focus()` as part of the document ready would work well... although turbolinks…
